In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

In [ ]:
df=pd.read_csv('HR case study.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302 entries, 0 to 301
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   linkedin_id        302 non-null    int64
 1   job_title          302 non-null    object
 2   contract           302 non-null    object
 3   mode               287 non-null    object
 4   city               280 non-null    object
 5   country            302 non-null    object
 6   company            302 non-null    object
 7   sector             302 non-null    object
 8   job_posting_title  302 non-null    object
 9   description        302 non-null    object
 10  linkedin_skills    302 non-null    object
dtypes: int64(1), object(10)
memory usage: 26.1+ KB

In [ ]:
df.head()

,linkedin_id,job_title,contract,mode,city,country,company,sector,job_posting_title,description,linkedin_skills
0,3629542706,Data Analyst,Full-time,On-site,Oldenburg,Germany,hanfried Personaldienstleistungen GmbH,Staffing & Recruiting,Data Analyst Finance (m/w/d) in Direktvermittlung,"Personalberatung, -überlassung oder -vermittlu...","Visual Basic, SQL, Data Visualization, Data An..."
1,3580242005,Data Analyst,Full-time,On-site,NaN,Italy,Telebit SpA,Telecommunications,LOGISTIC PROCESS & DATA ANALYST,"TELEBIT gruppo italiano moderno, solido, di gr...","Analytical Skills, Data Visualization, Data An..."
2,3570731003,Data Specialist,Full-time,Hybrid,Milan,Italy,NTT DATA Italia,Information Technology & Services,Data Driven Transformation Specialist,"NTT DATA, Trusted Global Innovator, è tra i pr...","Data Governance, Data Analytics, Analytics, Da..."
3,3587767744,Data Analyst,Full-time,Hybrid,Prague,Czechia,Aon,Financial Services,Junior Data Analyst,"Life is full of risks, from unexpected hurrica...","Data Visualization, Data Analytics, Visualizat..."
4,3625424422,Financial Analyst,Full-time,On-site,Madrid,Spain,BNP Paribas CIB,Financial Services,Financial Analyst CIB BL STEERING | BNP Pariba...,BNP Paribas EMEA Finance employs 500 employees...,"Ad Hoc Analysis, Business Requirements, Financ..."

In [ ]:
df.isnull().sum()

linkedin_id           0
job_title             0
contract              0
mode                 15
city                 22
country               0
company               0
sector                0
job_posting_title     0
description           0
linkedin_skills       0
dtype: int64

In [ ]:
df.isnull().sum()

linkedin_id          0
job_title            0
contract             0
mode                 0
city                 0
country              0
company              0
sector               0
job_posting_title    0
description          0
linkedin_skills      0
skills_list          0
dtype: int64

In [ ]:
df.columns

Index(['linkedin_id', 'job_title', 'contract', 'mode', 'city', 'country',
       'company', 'sector', 'job_posting_title', 'description',
       'linkedin_skills'],
      dtype='object')

In [ ]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
df.columns

Index(['linkedin_id', 'job_title', 'contract', 'mode', 'city', 'country',
       'company', 'sector', 'job_posting_title', 'description',
       'linkedin_skills'],
      dtype='object')

In [ ]:
df = df.dropna()

In [ ]:
df = df.fillna("Unknown")

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df['job_title'] = df['job_title'].str.strip()
df['company'] = df['company'].str.strip()
df['city'] = df['city'].str.strip()

In [ ]:
df['mode'].value_counts()

mode
On-site    160
Hybrid      87
Remote      18
Name: count, dtype: int64

In [ ]:
df['linkedin_skills'] = df['linkedin_skills'].str.lower()

In [ ]:
df['skills_list'] = df['linkedin_skills'].str.split(',')

In [ ]:
df.shape

(265, 12)

In [ ]:
df['job_title'].value_counts().head(10)

job_title
Data Analyst                        113
Data Specialist                      25
Analyst                              20
Financial Analyst                    18
Business Intelligence Specialist     10
Junior Business Analyst               8
Digital Analyst                       7
Business Analyst                      6
Analytics Specialist                  6
Quality Control Analyst               6
Name: count, dtype: int64

In [ ]:
df['company'].nunique()

227

In [ ]:
df['company'].value_counts().head(10)

company
Appen              9
BNP Paribas CIB    4
BNP Paribas        4
Walters People     4
Deloitte           4
Adecco             3
Carrefour          3
permanent tsb      2
Michael Page       2
Axians Portugal    2
Name: count, dtype: int64

In [ ]:
df['mode'].value_counts(normalize=True) * 100

mode
On-site    60.377358
Hybrid     32.830189
Remote      6.792453
Name: proportion, dtype: float64

In [ ]:
df['contract'].value_counts(normalize=True) * 100

contract
Full-time    88.301887
Part-time     5.660377
Contract      4.905660
Temporary     1.132075
Name: proportion, dtype: float64

In [ ]:
all_skills = df['linkedin_skills'].str.split(',').explode()
all_skills = all_skills.str.strip()

In [ ]:
all_skills.value_counts().head(10)

linkedin_skills
data analytics        121
analytical skills     106
data visualization     84
communication          82
data analysis          72
databases              59
problem solving        55
analytics              49
statistics             46
data science           45
Name: count, dtype: int64

In [ ]:
df['skills_count'] = df['skills_list'].apply(len)
df['skills_count'].mean()

np.float64(9.667924528301887)

In [ ]:
df.groupby('sector')['skills_count'].mean().sort_values(ascending=False)

sector
Civil Engineering                        12.000000
Mechanical Or Industrial Engineering     12.000000
Medical Device                           12.000000
Telecommunications                       12.000000
Leisure, Travel & Tourism                12.000000
Hospital & Health Care                   11.333333
Translation & Localization               11.333333
Consumer Services                        11.000000
Government Administration                11.000000
Financial Services                       10.266667
Human Resources                          10.230769
Electrical & Electronic Manufacturing    10.000000
Biotechnology                            10.000000
Gambling & Casinos                       10.000000
Food & Beverages                         10.000000
Facilities Services                      10.000000
Computer Games                           10.000000
Consumer Goods                           10.000000
Computer Software                        10.000000
Apparel & Fashion                        10.000000
Accounting                               10.000000
Research                                 10.000000
Renewables & Environment                 10.000000
Military                                 10.000000
Railroad Manufacture                     10.000000
Internet                                 10.000000
International Trade & Development        10.000000
Investment Management                    10.000000
Entertainment                            10.000000
Machinery                                10.000000
Marketing & Advertising                  10.000000
Logistics & Supply Chain                 10.000000
Luxury Goods & Jewelry                   10.000000
Hospitality                              10.000000
Banking                                   9.923077
Management Consulting                     9.916667
Information Technology & Services         9.745455
Staffing & Recruiting                     9.609756
Wholesale                                 9.333333
Airlines/Aviation                         9.200000
Retail                                    9.125000
Automotive                                8.750000
Pharmaceuticals                           8.600000
Information Services                      8.500000
Transportation/Trucking/Railroad          8.000000
Oil & Energy                              7.000000
Farming                                   7.000000
Computer & Network Security               7.000000
Market Research                           6.000000
Events Services                           5.500000
Outsourcing/Offshoring                    5.000000
Consumer Electronics                      4.500000
Public Safety                             4.000000
Name: skills_count, dtype: float64

In [ ]:
df.to_csv("cleaned_hr_case_study.csv", index=False)

In [ ]:
from google.colab import files
files.download('cleaned_hr_case_study.csv')